### ISSUE TITLE
repeating events is not possible

### ISSUE THREAD

**Issue by Chilipp** [SORSE/sorse.github.io#275]
The current implementation does not cover the case, when an event is repeated (to cover a different timezone, for instance). This should be implemented via something like

```yaml
time:
  - - start: 2020-07-22T18:00:00Z
      end: 2020-07-22T21:00:00Z
    - start: 2020-07-23T18:00:00Z
      end: 2020-07-23T21:00:00Z
  - - start: 2020-07-23T09:00:00Z
      end: 2020-07-23T12:00:00Z
    - start: 2020-07-24T09:00:00Z
      end: 2020-07-24T12:00:00Z
```
in the frontmatter of the events.
